### ISSUE TITLE
problem with save new model in database

### ISSUE THREAD

**Issue by hamedmoody** [tareq1988/wp-eloquent#20]
hi
i create a model in wordpress but not save in database:

```
<?php
class Etekaf extends \WeDevs\ORM\Eloquent\Model {

}
$et = new Etekaf();
$et->name = 'my Name';
$et->save();
```

and static 'create' method error:

`Fatal error: Uncaught exception 'Illuminate\Database\Eloquent\MassAssignmentException' with message 'email' in C:\xampp\htdocs\daneshjooyar\wp-content\plugins\dyedd-extra-option\vendor\illuminate\database\Eloquent\Model.php:404 Stack trace: #0 C:\xampp\htdocs\daneshjooyar\wp-content\plugins\dyedd-extra-option\vendor\illuminate\database\Eloquent\Model.php(259): Illuminate\Database\Eloquent\Model->fill(Array) #1 C:\xampp\htdocs\daneshjooyar\wp-content\plugins\dyedd-extra-option\vendor\tareq1988\wp-eloquent\src\Eloquent\Model.php(19): Illuminate\Database\Eloquent\Model->__construct(Array) #2 C:\xampp\htdocs\daneshjooyar\wp-content\plugins\dyedd-extra-option\vendor\illuminate\database\Eloquent\Model.php(527): WeDevs\ORM\Eloquent\Model->__construct(Array) #3 C:\xampp\htdocs\daneshjooyar\wp-content\plugins\dyedd-extra-option\dyedd-extra-option.php(96): Illuminate\Database\Eloquent\Model::create(Array) #4 C:\xampp\htdocs\daneshjooyar\wp-settings.php(254): include_once('C:\\xampp\\htdocs...') #5 C:\xampp\htdocs\daneshjooyar\wp-co in C:\xampp\htdocs\daneshjooyar\wp-content\plugins\dyedd-extra-option\vendor\illuminate\database\Eloquent\Model.php on line 404`

**Comment by tareq1988** [comment]
Take a look [here](https://laravel.com/docs/5.1/eloquent#mass-assignment)
